version: '3.7'
services:
  allure-server:
    # For local debug #
    # build: .
    image: kochetkovma/allure-server:2.13.6
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/allure
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DATABASE: postgresql
      SPRING_JPA_HIBERNATE_DDL-AUTO: update # Careful! 'create' destroy data! https://stackoverflow.com/questions/21113154/spring-boot-ddl-auto-generator
      TMS_ENABLED: 'false'
      TMS_HOST: jira.localhost
      TMS_TOKEN: '<token-here>'
      TMS_DRYRUN: 'false'
    ports:
      - 8080:8080
    volumes:
      - ./ext:/ext:rw
      - ./allure-server-store:/allure:rw
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: allure
    ports:
      - 5432:5432
    volumes:
      - ./allure-server-store-db:/var/lib/postgresql/data:rw
